# Generated by Django 5.1.5 on 2025-02-10 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipe_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
